-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'SFTP_FILE_RECEIVED';
ALTER TYPE "AuditEventType" ADD VALUE 'SFTP_METADATA_VALIDATED';
ALTER TYPE "AuditEventType" ADD VALUE 'SFTP_VIRUS_SCAN_PASSED';
ALTER TYPE "AuditEventType" ADD VALUE 'SFTP_DOCUMENT_CREATED';
ALTER TYPE "AuditEventType" ADD VALUE 'SFTP_STORAGE_UPLOADED';
ALTER TYPE "AuditEventType" ADD VALUE 'SFTP_EMAIL_QUEUED';
ALTER TYPE "AuditEventType" ADD VALUE 'SFTP_INGESTION_COMPLETED';
ALTER TYPE "AuditEventType" ADD VALUE 'SFTP_INGESTION_FAILED';
