/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as VerifyRouteRouteImport } from './routes/verify/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginEmailVerificationRouteImport } from './routes/login/email-verification'
import { Route as VerifyTokenRouteRouteImport } from './routes/verify/$token/route'
import { Route as AuthenticatedDevRouteRouteImport } from './routes/_authenticated/dev/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as VerifyTokenIndexRouteImport } from './routes/verify/$token/index'
import { Route as AuthenticatedDevIndexRouteImport } from './routes/_authenticated/dev/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as VerifyTokenCompleteRouteImport } from './routes/verify/$token/complete'
import { Route as AuthenticatedDevServiceIdRouteImport } from './routes/_authenticated/dev/$serviceId'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminProcessErrorsIndexRouteImport } from './routes/_authenticated/admin/process-errors/index'
import { Route as AuthenticatedAdminFailedProcessErrorsIndexRouteImport } from './routes/_authenticated/admin/failed-process-errors/index'
import { Route as AuthenticatedAdminFailedAuditLogsIndexRouteImport } from './routes/_authenticated/admin/failed-audit-logs/index'
import { Route as AuthenticatedAdminDocumentsIndexRouteImport } from './routes/_authenticated/admin/documents/index'
import { Route as AuthenticatedAdminAuditLogsIndexRouteImport } from './routes/_authenticated/admin/audit-logs/index'
import { Route as AuthenticatedAdminDocumentsIdRouteImport } from './routes/_authenticated/admin/documents/$id'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRouteRoute = VerifyRouteRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginEmailVerificationRoute = LoginEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => LoginRouteRoute,
} as any)
const VerifyTokenRouteRoute = VerifyTokenRouteRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => VerifyRouteRoute,
} as any)
const AuthenticatedDevRouteRoute = AuthenticatedDevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VerifyTokenIndexRoute = VerifyTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerifyTokenRouteRoute,
} as any)
const AuthenticatedDevIndexRoute = AuthenticatedDevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDevRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const VerifyTokenCompleteRoute = VerifyTokenCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => VerifyTokenRouteRoute,
} as any)
const AuthenticatedDevServiceIdRoute =
  AuthenticatedDevServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => AuthenticatedDevRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProcessErrorsIndexRoute =
  AuthenticatedAdminProcessErrorsIndexRouteImport.update({
    id: '/process-errors/',
    path: '/process-errors/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFailedProcessErrorsIndexRoute =
  AuthenticatedAdminFailedProcessErrorsIndexRouteImport.update({
    id: '/failed-process-errors/',
    path: '/failed-process-errors/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFailedAuditLogsIndexRoute =
  AuthenticatedAdminFailedAuditLogsIndexRouteImport.update({
    id: '/failed-audit-logs/',
    path: '/failed-audit-logs/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsIndexRoute =
  AuthenticatedAdminDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogsIndexRoute =
  AuthenticatedAdminAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsIdRoute =
  AuthenticatedAdminDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/verify': typeof VerifyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dev': typeof AuthenticatedDevRouteRouteWithChildren
  '/verify/$token': typeof VerifyTokenRouteRouteWithChildren
  '/login/email-verification': typeof LoginEmailVerificationRoute
  '/login/': typeof LoginIndexRoute
  '/dev/$serviceId': typeof AuthenticatedDevServiceIdRoute
  '/verify/$token/complete': typeof VerifyTokenCompleteRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dev/': typeof AuthenticatedDevIndexRoute
  '/verify/$token/': typeof VerifyTokenIndexRoute
  '/admin/documents/$id': typeof AuthenticatedAdminDocumentsIdRoute
  '/admin/audit-logs/': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/admin/documents/': typeof AuthenticatedAdminDocumentsIndexRoute
  '/admin/failed-audit-logs/': typeof AuthenticatedAdminFailedAuditLogsIndexRoute
  '/admin/failed-process-errors/': typeof AuthenticatedAdminFailedProcessErrorsIndexRoute
  '/admin/process-errors/': typeof AuthenticatedAdminProcessErrorsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify': typeof VerifyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/login/email-verification': typeof LoginEmailVerificationRoute
  '/login': typeof LoginIndexRoute
  '/dev/$serviceId': typeof AuthenticatedDevServiceIdRoute
  '/verify/$token/complete': typeof VerifyTokenCompleteRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dev': typeof AuthenticatedDevIndexRoute
  '/verify/$token': typeof VerifyTokenIndexRoute
  '/admin/documents/$id': typeof AuthenticatedAdminDocumentsIdRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsIndexRoute
  '/admin/failed-audit-logs': typeof AuthenticatedAdminFailedAuditLogsIndexRoute
  '/admin/failed-process-errors': typeof AuthenticatedAdminFailedProcessErrorsIndexRoute
  '/admin/process-errors': typeof AuthenticatedAdminProcessErrorsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/verify': typeof VerifyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dev': typeof AuthenticatedDevRouteRouteWithChildren
  '/verify/$token': typeof VerifyTokenRouteRouteWithChildren
  '/login/email-verification': typeof LoginEmailVerificationRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/dev/$serviceId': typeof AuthenticatedDevServiceIdRoute
  '/verify/$token/complete': typeof VerifyTokenCompleteRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dev/': typeof AuthenticatedDevIndexRoute
  '/verify/$token/': typeof VerifyTokenIndexRoute
  '/_authenticated/admin/documents/$id': typeof AuthenticatedAdminDocumentsIdRoute
  '/_authenticated/admin/audit-logs/': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/_authenticated/admin/documents/': typeof AuthenticatedAdminDocumentsIndexRoute
  '/_authenticated/admin/failed-audit-logs/': typeof AuthenticatedAdminFailedAuditLogsIndexRoute
  '/_authenticated/admin/failed-process-errors/': typeof AuthenticatedAdminFailedProcessErrorsIndexRoute
  '/_authenticated/admin/process-errors/': typeof AuthenticatedAdminProcessErrorsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/verify'
    | '/$'
    | '/admin'
    | '/dev'
    | '/verify/$token'
    | '/login/email-verification'
    | '/login/'
    | '/dev/$serviceId'
    | '/verify/$token/complete'
    | '/admin/'
    | '/dashboard/'
    | '/dev/'
    | '/verify/$token/'
    | '/admin/documents/$id'
    | '/admin/audit-logs/'
    | '/admin/documents/'
    | '/admin/failed-audit-logs/'
    | '/admin/failed-process-errors/'
    | '/admin/process-errors/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify'
    | '/$'
    | '/login/email-verification'
    | '/login'
    | '/dev/$serviceId'
    | '/verify/$token/complete'
    | '/admin'
    | '/dashboard'
    | '/dev'
    | '/verify/$token'
    | '/admin/documents/$id'
    | '/admin/audit-logs'
    | '/admin/documents'
    | '/admin/failed-audit-logs'
    | '/admin/failed-process-errors'
    | '/admin/process-errors'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/verify'
    | '/$'
    | '/_authenticated/admin'
    | '/_authenticated/dev'
    | '/verify/$token'
    | '/login/email-verification'
    | '/login/'
    | '/_authenticated/dev/$serviceId'
    | '/verify/$token/complete'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dev/'
    | '/verify/$token/'
    | '/_authenticated/admin/documents/$id'
    | '/_authenticated/admin/audit-logs/'
    | '/_authenticated/admin/documents/'
    | '/_authenticated/admin/failed-audit-logs/'
    | '/_authenticated/admin/failed-process-errors/'
    | '/_authenticated/admin/process-errors/'
    | '/_authenticated/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  VerifyRouteRoute: typeof VerifyRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/email-verification': {
      id: '/login/email-verification'
      path: '/email-verification'
      fullPath: '/login/email-verification'
      preLoaderRoute: typeof LoginEmailVerificationRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteRouteImport
      parentRoute: typeof VerifyRouteRoute
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verify/$token/': {
      id: '/verify/$token/'
      path: '/'
      fullPath: '/verify/$token/'
      preLoaderRoute: typeof VerifyTokenIndexRouteImport
      parentRoute: typeof VerifyTokenRouteRoute
    }
    '/_authenticated/dev/': {
      id: '/_authenticated/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof AuthenticatedDevIndexRouteImport
      parentRoute: typeof AuthenticatedDevRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/verify/$token/complete': {
      id: '/verify/$token/complete'
      path: '/complete'
      fullPath: '/verify/$token/complete'
      preLoaderRoute: typeof VerifyTokenCompleteRouteImport
      parentRoute: typeof VerifyTokenRouteRoute
    }
    '/_authenticated/dev/$serviceId': {
      id: '/_authenticated/dev/$serviceId'
      path: '/$serviceId'
      fullPath: '/dev/$serviceId'
      preLoaderRoute: typeof AuthenticatedDevServiceIdRouteImport
      parentRoute: typeof AuthenticatedDevRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/process-errors/': {
      id: '/_authenticated/admin/process-errors/'
      path: '/process-errors'
      fullPath: '/admin/process-errors/'
      preLoaderRoute: typeof AuthenticatedAdminProcessErrorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/failed-process-errors/': {
      id: '/_authenticated/admin/failed-process-errors/'
      path: '/failed-process-errors'
      fullPath: '/admin/failed-process-errors/'
      preLoaderRoute: typeof AuthenticatedAdminFailedProcessErrorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/failed-audit-logs/': {
      id: '/_authenticated/admin/failed-audit-logs/'
      path: '/failed-audit-logs'
      fullPath: '/admin/failed-audit-logs/'
      preLoaderRoute: typeof AuthenticatedAdminFailedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/documents/': {
      id: '/_authenticated/admin/documents/'
      path: '/documents'
      fullPath: '/admin/documents/'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-logs/': {
      id: '/_authenticated/admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/documents/$id': {
      id: '/_authenticated/admin/documents/$id'
      path: '/documents/$id'
      fullPath: '/admin/documents/$id'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminDocumentsIdRoute: typeof AuthenticatedAdminDocumentsIdRoute
  AuthenticatedAdminAuditLogsIndexRoute: typeof AuthenticatedAdminAuditLogsIndexRoute
  AuthenticatedAdminDocumentsIndexRoute: typeof AuthenticatedAdminDocumentsIndexRoute
  AuthenticatedAdminFailedAuditLogsIndexRoute: typeof AuthenticatedAdminFailedAuditLogsIndexRoute
  AuthenticatedAdminFailedProcessErrorsIndexRoute: typeof AuthenticatedAdminFailedProcessErrorsIndexRoute
  AuthenticatedAdminProcessErrorsIndexRoute: typeof AuthenticatedAdminProcessErrorsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminDocumentsIdRoute: AuthenticatedAdminDocumentsIdRoute,
    AuthenticatedAdminAuditLogsIndexRoute:
      AuthenticatedAdminAuditLogsIndexRoute,
    AuthenticatedAdminDocumentsIndexRoute:
      AuthenticatedAdminDocumentsIndexRoute,
    AuthenticatedAdminFailedAuditLogsIndexRoute:
      AuthenticatedAdminFailedAuditLogsIndexRoute,
    AuthenticatedAdminFailedProcessErrorsIndexRoute:
      AuthenticatedAdminFailedProcessErrorsIndexRoute,
    AuthenticatedAdminProcessErrorsIndexRoute:
      AuthenticatedAdminProcessErrorsIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDevRouteRouteChildren {
  AuthenticatedDevServiceIdRoute: typeof AuthenticatedDevServiceIdRoute
  AuthenticatedDevIndexRoute: typeof AuthenticatedDevIndexRoute
}

const AuthenticatedDevRouteRouteChildren: AuthenticatedDevRouteRouteChildren = {
  AuthenticatedDevServiceIdRoute: AuthenticatedDevServiceIdRoute,
  AuthenticatedDevIndexRoute: AuthenticatedDevIndexRoute,
}

const AuthenticatedDevRouteRouteWithChildren =
  AuthenticatedDevRouteRoute._addFileChildren(
    AuthenticatedDevRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDevRouteRoute: typeof AuthenticatedDevRouteRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDevRouteRoute: AuthenticatedDevRouteRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LoginRouteRouteChildren {
  LoginEmailVerificationRoute: typeof LoginEmailVerificationRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginEmailVerificationRoute: LoginEmailVerificationRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface VerifyTokenRouteRouteChildren {
  VerifyTokenCompleteRoute: typeof VerifyTokenCompleteRoute
  VerifyTokenIndexRoute: typeof VerifyTokenIndexRoute
}

const VerifyTokenRouteRouteChildren: VerifyTokenRouteRouteChildren = {
  VerifyTokenCompleteRoute: VerifyTokenCompleteRoute,
  VerifyTokenIndexRoute: VerifyTokenIndexRoute,
}

const VerifyTokenRouteRouteWithChildren =
  VerifyTokenRouteRoute._addFileChildren(VerifyTokenRouteRouteChildren)

interface VerifyRouteRouteChildren {
  VerifyTokenRouteRoute: typeof VerifyTokenRouteRouteWithChildren
}

const VerifyRouteRouteChildren: VerifyRouteRouteChildren = {
  VerifyTokenRouteRoute: VerifyTokenRouteRouteWithChildren,
}

const VerifyRouteRouteWithChildren = VerifyRouteRoute._addFileChildren(
  VerifyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  VerifyRouteRoute: VerifyRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
