/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as VerifyRouteRouteImport } from './routes/verify/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginEmailVerificationRouteImport } from './routes/login/email-verification'
import { Route as VerifyTokenRouteRouteImport } from './routes/verify/$token/route'
import { Route as AuthenticatedDevRouteRouteImport } from './routes/_authenticated/dev/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as VerifyTokenIndexRouteImport } from './routes/verify/$token/index'
import { Route as AuthenticatedDevIndexRouteImport } from './routes/_authenticated/dev/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as VerifyTokenCompleteRouteImport } from './routes/verify/$token/complete'
import { Route as AuthenticatedDevServiceIdRouteImport } from './routes/_authenticated/dev/$serviceId'
import { Route as AuthenticatedAdminWebhookDeliveriesIndexRouteImport } from './routes/_authenticated/admin/webhook-deliveries/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminRecipientsIndexRouteImport } from './routes/_authenticated/admin/recipients/index'
import { Route as AuthenticatedAdminProcessErrorsIndexRouteImport } from './routes/_authenticated/admin/process-errors/index'
import { Route as AuthenticatedAdminFilesIndexRouteImport } from './routes/_authenticated/admin/files/index'
import { Route as AuthenticatedAdminFailedWebhookDeliveriesIndexRouteImport } from './routes/_authenticated/admin/failed-webhook-deliveries/index'
import { Route as AuthenticatedAdminFailedProcessErrorsIndexRouteImport } from './routes/_authenticated/admin/failed-process-errors/index'
import { Route as AuthenticatedAdminFailedAuditLogsIndexRouteImport } from './routes/_authenticated/admin/failed-audit-logs/index'
import { Route as AuthenticatedAdminDocumentsIndexRouteImport } from './routes/_authenticated/admin/documents/index'
import { Route as AuthenticatedAdminDocumentLinksIndexRouteImport } from './routes/_authenticated/admin/document-links/index'
import { Route as AuthenticatedAdminDocumentFilesIndexRouteImport } from './routes/_authenticated/admin/document-files/index'
import { Route as AuthenticatedAdminDeadLettersIndexRouteImport } from './routes/_authenticated/admin/dead-letters/index'
import { Route as AuthenticatedAdminCommunicationsIndexRouteImport } from './routes/_authenticated/admin/communications/index'
import { Route as AuthenticatedAdminAuditLogsIndexRouteImport } from './routes/_authenticated/admin/audit-logs/index'
import { Route as AuthenticatedAdminRecipientsIdRouteImport } from './routes/_authenticated/admin/recipients/$id'
import { Route as AuthenticatedAdminFilesIdRouteImport } from './routes/_authenticated/admin/files/$id'
import { Route as AuthenticatedAdminDocumentsIdRouteImport } from './routes/_authenticated/admin/documents/$id'
import { Route as AuthenticatedAdminDocumentLinksIdRouteImport } from './routes/_authenticated/admin/document-links/$id'
import { Route as AuthenticatedAdminDocumentFilesIdRouteImport } from './routes/_authenticated/admin/document-files/$id'
import { Route as AuthenticatedAdminCommunicationsIdRouteImport } from './routes/_authenticated/admin/communications/$id'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRouteRoute = VerifyRouteRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginEmailVerificationRoute = LoginEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => LoginRouteRoute,
} as any)
const VerifyTokenRouteRoute = VerifyTokenRouteRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => VerifyRouteRoute,
} as any)
const AuthenticatedDevRouteRoute = AuthenticatedDevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VerifyTokenIndexRoute = VerifyTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerifyTokenRouteRoute,
} as any)
const AuthenticatedDevIndexRoute = AuthenticatedDevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDevRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const VerifyTokenCompleteRoute = VerifyTokenCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => VerifyTokenRouteRoute,
} as any)
const AuthenticatedDevServiceIdRoute =
  AuthenticatedDevServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => AuthenticatedDevRouteRoute,
  } as any)
const AuthenticatedAdminWebhookDeliveriesIndexRoute =
  AuthenticatedAdminWebhookDeliveriesIndexRouteImport.update({
    id: '/webhook-deliveries/',
    path: '/webhook-deliveries/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRecipientsIndexRoute =
  AuthenticatedAdminRecipientsIndexRouteImport.update({
    id: '/recipients/',
    path: '/recipients/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProcessErrorsIndexRoute =
  AuthenticatedAdminProcessErrorsIndexRouteImport.update({
    id: '/process-errors/',
    path: '/process-errors/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFilesIndexRoute =
  AuthenticatedAdminFilesIndexRouteImport.update({
    id: '/files/',
    path: '/files/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFailedWebhookDeliveriesIndexRoute =
  AuthenticatedAdminFailedWebhookDeliveriesIndexRouteImport.update({
    id: '/failed-webhook-deliveries/',
    path: '/failed-webhook-deliveries/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFailedProcessErrorsIndexRoute =
  AuthenticatedAdminFailedProcessErrorsIndexRouteImport.update({
    id: '/failed-process-errors/',
    path: '/failed-process-errors/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFailedAuditLogsIndexRoute =
  AuthenticatedAdminFailedAuditLogsIndexRouteImport.update({
    id: '/failed-audit-logs/',
    path: '/failed-audit-logs/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsIndexRoute =
  AuthenticatedAdminDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentLinksIndexRoute =
  AuthenticatedAdminDocumentLinksIndexRouteImport.update({
    id: '/document-links/',
    path: '/document-links/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentFilesIndexRoute =
  AuthenticatedAdminDocumentFilesIndexRouteImport.update({
    id: '/document-files/',
    path: '/document-files/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDeadLettersIndexRoute =
  AuthenticatedAdminDeadLettersIndexRouteImport.update({
    id: '/dead-letters/',
    path: '/dead-letters/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommunicationsIndexRoute =
  AuthenticatedAdminCommunicationsIndexRouteImport.update({
    id: '/communications/',
    path: '/communications/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogsIndexRoute =
  AuthenticatedAdminAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRecipientsIdRoute =
  AuthenticatedAdminRecipientsIdRouteImport.update({
    id: '/recipients/$id',
    path: '/recipients/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFilesIdRoute =
  AuthenticatedAdminFilesIdRouteImport.update({
    id: '/files/$id',
    path: '/files/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentsIdRoute =
  AuthenticatedAdminDocumentsIdRouteImport.update({
    id: '/documents/$id',
    path: '/documents/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentLinksIdRoute =
  AuthenticatedAdminDocumentLinksIdRouteImport.update({
    id: '/document-links/$id',
    path: '/document-links/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDocumentFilesIdRoute =
  AuthenticatedAdminDocumentFilesIdRouteImport.update({
    id: '/document-files/$id',
    path: '/document-files/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommunicationsIdRoute =
  AuthenticatedAdminCommunicationsIdRouteImport.update({
    id: '/communications/$id',
    path: '/communications/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/verify': typeof VerifyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dev': typeof AuthenticatedDevRouteRouteWithChildren
  '/verify/$token': typeof VerifyTokenRouteRouteWithChildren
  '/login/email-verification': typeof LoginEmailVerificationRoute
  '/login/': typeof LoginIndexRoute
  '/dev/$serviceId': typeof AuthenticatedDevServiceIdRoute
  '/verify/$token/complete': typeof VerifyTokenCompleteRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dev/': typeof AuthenticatedDevIndexRoute
  '/verify/$token/': typeof VerifyTokenIndexRoute
  '/admin/communications/$id': typeof AuthenticatedAdminCommunicationsIdRoute
  '/admin/document-files/$id': typeof AuthenticatedAdminDocumentFilesIdRoute
  '/admin/document-links/$id': typeof AuthenticatedAdminDocumentLinksIdRoute
  '/admin/documents/$id': typeof AuthenticatedAdminDocumentsIdRoute
  '/admin/files/$id': typeof AuthenticatedAdminFilesIdRoute
  '/admin/recipients/$id': typeof AuthenticatedAdminRecipientsIdRoute
  '/admin/audit-logs/': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/admin/communications/': typeof AuthenticatedAdminCommunicationsIndexRoute
  '/admin/dead-letters/': typeof AuthenticatedAdminDeadLettersIndexRoute
  '/admin/document-files/': typeof AuthenticatedAdminDocumentFilesIndexRoute
  '/admin/document-links/': typeof AuthenticatedAdminDocumentLinksIndexRoute
  '/admin/documents/': typeof AuthenticatedAdminDocumentsIndexRoute
  '/admin/failed-audit-logs/': typeof AuthenticatedAdminFailedAuditLogsIndexRoute
  '/admin/failed-process-errors/': typeof AuthenticatedAdminFailedProcessErrorsIndexRoute
  '/admin/failed-webhook-deliveries/': typeof AuthenticatedAdminFailedWebhookDeliveriesIndexRoute
  '/admin/files/': typeof AuthenticatedAdminFilesIndexRoute
  '/admin/process-errors/': typeof AuthenticatedAdminProcessErrorsIndexRoute
  '/admin/recipients/': typeof AuthenticatedAdminRecipientsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/webhook-deliveries/': typeof AuthenticatedAdminWebhookDeliveriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify': typeof VerifyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/login/email-verification': typeof LoginEmailVerificationRoute
  '/login': typeof LoginIndexRoute
  '/dev/$serviceId': typeof AuthenticatedDevServiceIdRoute
  '/verify/$token/complete': typeof VerifyTokenCompleteRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dev': typeof AuthenticatedDevIndexRoute
  '/verify/$token': typeof VerifyTokenIndexRoute
  '/admin/communications/$id': typeof AuthenticatedAdminCommunicationsIdRoute
  '/admin/document-files/$id': typeof AuthenticatedAdminDocumentFilesIdRoute
  '/admin/document-links/$id': typeof AuthenticatedAdminDocumentLinksIdRoute
  '/admin/documents/$id': typeof AuthenticatedAdminDocumentsIdRoute
  '/admin/files/$id': typeof AuthenticatedAdminFilesIdRoute
  '/admin/recipients/$id': typeof AuthenticatedAdminRecipientsIdRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/admin/communications': typeof AuthenticatedAdminCommunicationsIndexRoute
  '/admin/dead-letters': typeof AuthenticatedAdminDeadLettersIndexRoute
  '/admin/document-files': typeof AuthenticatedAdminDocumentFilesIndexRoute
  '/admin/document-links': typeof AuthenticatedAdminDocumentLinksIndexRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsIndexRoute
  '/admin/failed-audit-logs': typeof AuthenticatedAdminFailedAuditLogsIndexRoute
  '/admin/failed-process-errors': typeof AuthenticatedAdminFailedProcessErrorsIndexRoute
  '/admin/failed-webhook-deliveries': typeof AuthenticatedAdminFailedWebhookDeliveriesIndexRoute
  '/admin/files': typeof AuthenticatedAdminFilesIndexRoute
  '/admin/process-errors': typeof AuthenticatedAdminProcessErrorsIndexRoute
  '/admin/recipients': typeof AuthenticatedAdminRecipientsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/webhook-deliveries': typeof AuthenticatedAdminWebhookDeliveriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/verify': typeof VerifyRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dev': typeof AuthenticatedDevRouteRouteWithChildren
  '/verify/$token': typeof VerifyTokenRouteRouteWithChildren
  '/login/email-verification': typeof LoginEmailVerificationRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/dev/$serviceId': typeof AuthenticatedDevServiceIdRoute
  '/verify/$token/complete': typeof VerifyTokenCompleteRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dev/': typeof AuthenticatedDevIndexRoute
  '/verify/$token/': typeof VerifyTokenIndexRoute
  '/_authenticated/admin/communications/$id': typeof AuthenticatedAdminCommunicationsIdRoute
  '/_authenticated/admin/document-files/$id': typeof AuthenticatedAdminDocumentFilesIdRoute
  '/_authenticated/admin/document-links/$id': typeof AuthenticatedAdminDocumentLinksIdRoute
  '/_authenticated/admin/documents/$id': typeof AuthenticatedAdminDocumentsIdRoute
  '/_authenticated/admin/files/$id': typeof AuthenticatedAdminFilesIdRoute
  '/_authenticated/admin/recipients/$id': typeof AuthenticatedAdminRecipientsIdRoute
  '/_authenticated/admin/audit-logs/': typeof AuthenticatedAdminAuditLogsIndexRoute
  '/_authenticated/admin/communications/': typeof AuthenticatedAdminCommunicationsIndexRoute
  '/_authenticated/admin/dead-letters/': typeof AuthenticatedAdminDeadLettersIndexRoute
  '/_authenticated/admin/document-files/': typeof AuthenticatedAdminDocumentFilesIndexRoute
  '/_authenticated/admin/document-links/': typeof AuthenticatedAdminDocumentLinksIndexRoute
  '/_authenticated/admin/documents/': typeof AuthenticatedAdminDocumentsIndexRoute
  '/_authenticated/admin/failed-audit-logs/': typeof AuthenticatedAdminFailedAuditLogsIndexRoute
  '/_authenticated/admin/failed-process-errors/': typeof AuthenticatedAdminFailedProcessErrorsIndexRoute
  '/_authenticated/admin/failed-webhook-deliveries/': typeof AuthenticatedAdminFailedWebhookDeliveriesIndexRoute
  '/_authenticated/admin/files/': typeof AuthenticatedAdminFilesIndexRoute
  '/_authenticated/admin/process-errors/': typeof AuthenticatedAdminProcessErrorsIndexRoute
  '/_authenticated/admin/recipients/': typeof AuthenticatedAdminRecipientsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/admin/webhook-deliveries/': typeof AuthenticatedAdminWebhookDeliveriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/verify'
    | '/$'
    | '/admin'
    | '/dev'
    | '/verify/$token'
    | '/login/email-verification'
    | '/login/'
    | '/dev/$serviceId'
    | '/verify/$token/complete'
    | '/admin/'
    | '/dashboard/'
    | '/dev/'
    | '/verify/$token/'
    | '/admin/communications/$id'
    | '/admin/document-files/$id'
    | '/admin/document-links/$id'
    | '/admin/documents/$id'
    | '/admin/files/$id'
    | '/admin/recipients/$id'
    | '/admin/audit-logs/'
    | '/admin/communications/'
    | '/admin/dead-letters/'
    | '/admin/document-files/'
    | '/admin/document-links/'
    | '/admin/documents/'
    | '/admin/failed-audit-logs/'
    | '/admin/failed-process-errors/'
    | '/admin/failed-webhook-deliveries/'
    | '/admin/files/'
    | '/admin/process-errors/'
    | '/admin/recipients/'
    | '/admin/users/'
    | '/admin/webhook-deliveries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify'
    | '/$'
    | '/login/email-verification'
    | '/login'
    | '/dev/$serviceId'
    | '/verify/$token/complete'
    | '/admin'
    | '/dashboard'
    | '/dev'
    | '/verify/$token'
    | '/admin/communications/$id'
    | '/admin/document-files/$id'
    | '/admin/document-links/$id'
    | '/admin/documents/$id'
    | '/admin/files/$id'
    | '/admin/recipients/$id'
    | '/admin/audit-logs'
    | '/admin/communications'
    | '/admin/dead-letters'
    | '/admin/document-files'
    | '/admin/document-links'
    | '/admin/documents'
    | '/admin/failed-audit-logs'
    | '/admin/failed-process-errors'
    | '/admin/failed-webhook-deliveries'
    | '/admin/files'
    | '/admin/process-errors'
    | '/admin/recipients'
    | '/admin/users'
    | '/admin/webhook-deliveries'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/verify'
    | '/$'
    | '/_authenticated/admin'
    | '/_authenticated/dev'
    | '/verify/$token'
    | '/login/email-verification'
    | '/login/'
    | '/_authenticated/dev/$serviceId'
    | '/verify/$token/complete'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dev/'
    | '/verify/$token/'
    | '/_authenticated/admin/communications/$id'
    | '/_authenticated/admin/document-files/$id'
    | '/_authenticated/admin/document-links/$id'
    | '/_authenticated/admin/documents/$id'
    | '/_authenticated/admin/files/$id'
    | '/_authenticated/admin/recipients/$id'
    | '/_authenticated/admin/audit-logs/'
    | '/_authenticated/admin/communications/'
    | '/_authenticated/admin/dead-letters/'
    | '/_authenticated/admin/document-files/'
    | '/_authenticated/admin/document-links/'
    | '/_authenticated/admin/documents/'
    | '/_authenticated/admin/failed-audit-logs/'
    | '/_authenticated/admin/failed-process-errors/'
    | '/_authenticated/admin/failed-webhook-deliveries/'
    | '/_authenticated/admin/files/'
    | '/_authenticated/admin/process-errors/'
    | '/_authenticated/admin/recipients/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/admin/webhook-deliveries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  VerifyRouteRoute: typeof VerifyRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/email-verification': {
      id: '/login/email-verification'
      path: '/email-verification'
      fullPath: '/login/email-verification'
      preLoaderRoute: typeof LoginEmailVerificationRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteRouteImport
      parentRoute: typeof VerifyRouteRoute
    }
    '/_authenticated/dev': {
      id: '/_authenticated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof AuthenticatedDevRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verify/$token/': {
      id: '/verify/$token/'
      path: '/'
      fullPath: '/verify/$token/'
      preLoaderRoute: typeof VerifyTokenIndexRouteImport
      parentRoute: typeof VerifyTokenRouteRoute
    }
    '/_authenticated/dev/': {
      id: '/_authenticated/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof AuthenticatedDevIndexRouteImport
      parentRoute: typeof AuthenticatedDevRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/verify/$token/complete': {
      id: '/verify/$token/complete'
      path: '/complete'
      fullPath: '/verify/$token/complete'
      preLoaderRoute: typeof VerifyTokenCompleteRouteImport
      parentRoute: typeof VerifyTokenRouteRoute
    }
    '/_authenticated/dev/$serviceId': {
      id: '/_authenticated/dev/$serviceId'
      path: '/$serviceId'
      fullPath: '/dev/$serviceId'
      preLoaderRoute: typeof AuthenticatedDevServiceIdRouteImport
      parentRoute: typeof AuthenticatedDevRouteRoute
    }
    '/_authenticated/admin/webhook-deliveries/': {
      id: '/_authenticated/admin/webhook-deliveries/'
      path: '/webhook-deliveries'
      fullPath: '/admin/webhook-deliveries/'
      preLoaderRoute: typeof AuthenticatedAdminWebhookDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/recipients/': {
      id: '/_authenticated/admin/recipients/'
      path: '/recipients'
      fullPath: '/admin/recipients/'
      preLoaderRoute: typeof AuthenticatedAdminRecipientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/process-errors/': {
      id: '/_authenticated/admin/process-errors/'
      path: '/process-errors'
      fullPath: '/admin/process-errors/'
      preLoaderRoute: typeof AuthenticatedAdminProcessErrorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/files/': {
      id: '/_authenticated/admin/files/'
      path: '/files'
      fullPath: '/admin/files/'
      preLoaderRoute: typeof AuthenticatedAdminFilesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/failed-webhook-deliveries/': {
      id: '/_authenticated/admin/failed-webhook-deliveries/'
      path: '/failed-webhook-deliveries'
      fullPath: '/admin/failed-webhook-deliveries/'
      preLoaderRoute: typeof AuthenticatedAdminFailedWebhookDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/failed-process-errors/': {
      id: '/_authenticated/admin/failed-process-errors/'
      path: '/failed-process-errors'
      fullPath: '/admin/failed-process-errors/'
      preLoaderRoute: typeof AuthenticatedAdminFailedProcessErrorsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/failed-audit-logs/': {
      id: '/_authenticated/admin/failed-audit-logs/'
      path: '/failed-audit-logs'
      fullPath: '/admin/failed-audit-logs/'
      preLoaderRoute: typeof AuthenticatedAdminFailedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/documents/': {
      id: '/_authenticated/admin/documents/'
      path: '/documents'
      fullPath: '/admin/documents/'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/document-links/': {
      id: '/_authenticated/admin/document-links/'
      path: '/document-links'
      fullPath: '/admin/document-links/'
      preLoaderRoute: typeof AuthenticatedAdminDocumentLinksIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/document-files/': {
      id: '/_authenticated/admin/document-files/'
      path: '/document-files'
      fullPath: '/admin/document-files/'
      preLoaderRoute: typeof AuthenticatedAdminDocumentFilesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dead-letters/': {
      id: '/_authenticated/admin/dead-letters/'
      path: '/dead-letters'
      fullPath: '/admin/dead-letters/'
      preLoaderRoute: typeof AuthenticatedAdminDeadLettersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/communications/': {
      id: '/_authenticated/admin/communications/'
      path: '/communications'
      fullPath: '/admin/communications/'
      preLoaderRoute: typeof AuthenticatedAdminCommunicationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-logs/': {
      id: '/_authenticated/admin/audit-logs/'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/recipients/$id': {
      id: '/_authenticated/admin/recipients/$id'
      path: '/recipients/$id'
      fullPath: '/admin/recipients/$id'
      preLoaderRoute: typeof AuthenticatedAdminRecipientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/files/$id': {
      id: '/_authenticated/admin/files/$id'
      path: '/files/$id'
      fullPath: '/admin/files/$id'
      preLoaderRoute: typeof AuthenticatedAdminFilesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/documents/$id': {
      id: '/_authenticated/admin/documents/$id'
      path: '/documents/$id'
      fullPath: '/admin/documents/$id'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/document-links/$id': {
      id: '/_authenticated/admin/document-links/$id'
      path: '/document-links/$id'
      fullPath: '/admin/document-links/$id'
      preLoaderRoute: typeof AuthenticatedAdminDocumentLinksIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/document-files/$id': {
      id: '/_authenticated/admin/document-files/$id'
      path: '/document-files/$id'
      fullPath: '/admin/document-files/$id'
      preLoaderRoute: typeof AuthenticatedAdminDocumentFilesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/communications/$id': {
      id: '/_authenticated/admin/communications/$id'
      path: '/communications/$id'
      fullPath: '/admin/communications/$id'
      preLoaderRoute: typeof AuthenticatedAdminCommunicationsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCommunicationsIdRoute: typeof AuthenticatedAdminCommunicationsIdRoute
  AuthenticatedAdminDocumentFilesIdRoute: typeof AuthenticatedAdminDocumentFilesIdRoute
  AuthenticatedAdminDocumentLinksIdRoute: typeof AuthenticatedAdminDocumentLinksIdRoute
  AuthenticatedAdminDocumentsIdRoute: typeof AuthenticatedAdminDocumentsIdRoute
  AuthenticatedAdminFilesIdRoute: typeof AuthenticatedAdminFilesIdRoute
  AuthenticatedAdminRecipientsIdRoute: typeof AuthenticatedAdminRecipientsIdRoute
  AuthenticatedAdminAuditLogsIndexRoute: typeof AuthenticatedAdminAuditLogsIndexRoute
  AuthenticatedAdminCommunicationsIndexRoute: typeof AuthenticatedAdminCommunicationsIndexRoute
  AuthenticatedAdminDeadLettersIndexRoute: typeof AuthenticatedAdminDeadLettersIndexRoute
  AuthenticatedAdminDocumentFilesIndexRoute: typeof AuthenticatedAdminDocumentFilesIndexRoute
  AuthenticatedAdminDocumentLinksIndexRoute: typeof AuthenticatedAdminDocumentLinksIndexRoute
  AuthenticatedAdminDocumentsIndexRoute: typeof AuthenticatedAdminDocumentsIndexRoute
  AuthenticatedAdminFailedAuditLogsIndexRoute: typeof AuthenticatedAdminFailedAuditLogsIndexRoute
  AuthenticatedAdminFailedProcessErrorsIndexRoute: typeof AuthenticatedAdminFailedProcessErrorsIndexRoute
  AuthenticatedAdminFailedWebhookDeliveriesIndexRoute: typeof AuthenticatedAdminFailedWebhookDeliveriesIndexRoute
  AuthenticatedAdminFilesIndexRoute: typeof AuthenticatedAdminFilesIndexRoute
  AuthenticatedAdminProcessErrorsIndexRoute: typeof AuthenticatedAdminProcessErrorsIndexRoute
  AuthenticatedAdminRecipientsIndexRoute: typeof AuthenticatedAdminRecipientsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminWebhookDeliveriesIndexRoute: typeof AuthenticatedAdminWebhookDeliveriesIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCommunicationsIdRoute:
      AuthenticatedAdminCommunicationsIdRoute,
    AuthenticatedAdminDocumentFilesIdRoute:
      AuthenticatedAdminDocumentFilesIdRoute,
    AuthenticatedAdminDocumentLinksIdRoute:
      AuthenticatedAdminDocumentLinksIdRoute,
    AuthenticatedAdminDocumentsIdRoute: AuthenticatedAdminDocumentsIdRoute,
    AuthenticatedAdminFilesIdRoute: AuthenticatedAdminFilesIdRoute,
    AuthenticatedAdminRecipientsIdRoute: AuthenticatedAdminRecipientsIdRoute,
    AuthenticatedAdminAuditLogsIndexRoute:
      AuthenticatedAdminAuditLogsIndexRoute,
    AuthenticatedAdminCommunicationsIndexRoute:
      AuthenticatedAdminCommunicationsIndexRoute,
    AuthenticatedAdminDeadLettersIndexRoute:
      AuthenticatedAdminDeadLettersIndexRoute,
    AuthenticatedAdminDocumentFilesIndexRoute:
      AuthenticatedAdminDocumentFilesIndexRoute,
    AuthenticatedAdminDocumentLinksIndexRoute:
      AuthenticatedAdminDocumentLinksIndexRoute,
    AuthenticatedAdminDocumentsIndexRoute:
      AuthenticatedAdminDocumentsIndexRoute,
    AuthenticatedAdminFailedAuditLogsIndexRoute:
      AuthenticatedAdminFailedAuditLogsIndexRoute,
    AuthenticatedAdminFailedProcessErrorsIndexRoute:
      AuthenticatedAdminFailedProcessErrorsIndexRoute,
    AuthenticatedAdminFailedWebhookDeliveriesIndexRoute:
      AuthenticatedAdminFailedWebhookDeliveriesIndexRoute,
    AuthenticatedAdminFilesIndexRoute: AuthenticatedAdminFilesIndexRoute,
    AuthenticatedAdminProcessErrorsIndexRoute:
      AuthenticatedAdminProcessErrorsIndexRoute,
    AuthenticatedAdminRecipientsIndexRoute:
      AuthenticatedAdminRecipientsIndexRoute,
    AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
    AuthenticatedAdminWebhookDeliveriesIndexRoute:
      AuthenticatedAdminWebhookDeliveriesIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDevRouteRouteChildren {
  AuthenticatedDevServiceIdRoute: typeof AuthenticatedDevServiceIdRoute
  AuthenticatedDevIndexRoute: typeof AuthenticatedDevIndexRoute
}

const AuthenticatedDevRouteRouteChildren: AuthenticatedDevRouteRouteChildren = {
  AuthenticatedDevServiceIdRoute: AuthenticatedDevServiceIdRoute,
  AuthenticatedDevIndexRoute: AuthenticatedDevIndexRoute,
}

const AuthenticatedDevRouteRouteWithChildren =
  AuthenticatedDevRouteRoute._addFileChildren(
    AuthenticatedDevRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDevRouteRoute: typeof AuthenticatedDevRouteRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDevRouteRoute: AuthenticatedDevRouteRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LoginRouteRouteChildren {
  LoginEmailVerificationRoute: typeof LoginEmailVerificationRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginEmailVerificationRoute: LoginEmailVerificationRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

interface VerifyTokenRouteRouteChildren {
  VerifyTokenCompleteRoute: typeof VerifyTokenCompleteRoute
  VerifyTokenIndexRoute: typeof VerifyTokenIndexRoute
}

const VerifyTokenRouteRouteChildren: VerifyTokenRouteRouteChildren = {
  VerifyTokenCompleteRoute: VerifyTokenCompleteRoute,
  VerifyTokenIndexRoute: VerifyTokenIndexRoute,
}

const VerifyTokenRouteRouteWithChildren =
  VerifyTokenRouteRoute._addFileChildren(VerifyTokenRouteRouteChildren)

interface VerifyRouteRouteChildren {
  VerifyTokenRouteRoute: typeof VerifyTokenRouteRouteWithChildren
}

const VerifyRouteRouteChildren: VerifyRouteRouteChildren = {
  VerifyTokenRouteRoute: VerifyTokenRouteRouteWithChildren,
}

const VerifyRouteRouteWithChildren = VerifyRouteRoute._addFileChildren(
  VerifyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  VerifyRouteRoute: VerifyRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
